backend:
  name: git-gateway
  branch: main

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "about"
    label: "About Page"
    files:
      - file: "src/content/about.md"
        label: "About Content"
        name: "about"
        fields:
          - { label: "Body", name: "body", widget: "markdown" }

  - name: "projects"
    label: "Projects"
    folder: "src/content/projects"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Category", name: "category", widget: "select", options: ["AI storytelling","Real Shot / Live Action","Virtual Production","Post Production"] }
      - { label: "Description", name: "description", widget: "markdown" }
